substitutions:
  <<: !include ../secrets.yaml
  esphome_name: m5_atom_01

esphome:
  name: ${esphome_name}
  platform: ESP32
  board: pico32
  platformio_options:
    upload_speed: 115200
  on_boot:
    - light.turn_on:
        id: led1
        brightness: 30%
        red: 0%
        green: 0%
        blue: 100%
    - wait_until:
        wifi.connected:
    - light.turn_off: led1
    - light.turn_on:
        id: led1
        brightness: 30%
        red: 0%
        green: 100%
        blue: 0%
    - wait_until:
        api.connected:
    - light.turn_off: led1
    - light.turn_on:
        id: led1
        brightness: 20%
        red: 0%
        green: 50%
        blue: 50%       

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${esphome_name}
    password: ${cap_passowrd}

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ${api_password}

ota:
  password: ${ota_password}

light:
  - platform: fastled_clockless
    chipset: WS2812
    rgb_order: GRB
    pin: GPIO27
    num_leds: 25
    name: ${esphome_name} Led Matrix
    id: led1

binary_sensor:
  - platform: homeassistant
    name: ${esphome_name} view 01
    id: view_01
    entity_id: binary_sensor.m5_lite_02_door
    on_press:
      then:
        - light.addressable_set:
            id: led1
            range_from: 0
            range_to: 4
            red: 100%
            green: 0%
            blue: 0%
    on_release:
      then:
        - light.addressable_set:
            id: led1
            range_from: 0
            range_to: 4
            red: 0%
            green: 100%
            blue: 100%       

  - platform: homeassistant
    name: ${esphome_name} view 02
    entity_id: binary_sensor.living_door
    on_press:
      then:
        - light.addressable_set:
            id: led1
            range_from: 5
            range_to: 9
            red: 100%
            green: 0%
            blue: 0%
    on_release:
      then:
        - light.addressable_set:
            id: led1
            range_from: 5
            range_to: 9
            red: 0%
            green: 100%
            blue: 100%   

  - platform: homeassistant
    name: ${esphome_name} view 03
    entity_id: binary_sensor.m5_lite_04_door_01
    on_press:
      then:
        - light.addressable_set:
            id: led1
            range_from: 10
            range_to: 14
            red: 100%
            green: 0%
            blue: 0%
    on_release:
      then:
        - light.addressable_set:
            id: led1
            range_from: 10
            range_to: 14
            red: 0%
            green: 100%
            blue: 100%   

  - platform: homeassistant
    name: ${esphome_name} view 04-1
    entity_id: binary_sensor.m5_lite_04_door_02
    on_press:
      then:
        - light.addressable_set:
            id: led1
            range_from: 15
            range_to: 17
            red: 100%
            green: 0%
            blue: 0%
    on_release:
      then:
        - light.addressable_set:
            id: led1
            range_from: 15
            range_to: 17
            red: 0%
            green: 100%
            blue: 100%  

  - platform: homeassistant
    name: ${esphome_name} view 04-2
    entity_id: binary_sensor.m5_lite_04_pir
    on_press:
      then:
        - light.addressable_set:
            id: led1
            range_from: 18
            range_to: 19
            red: 100%
            green: 0%
            blue: 0%
    on_release:
      then:
        - light.addressable_set:
            id: led1
            range_from: 18
            range_to: 19
            red: 0%
            green: 100%
            blue: 100%   

  - platform: homeassistant
    name: ${esphome_name} view 05
    entity_id: binary_sensor.ttgocam01_pir
    on_press:
      then:
        - light.addressable_set:
            id: led1
            range_from: 20
            range_to: 24
            red: 100%
            green: 0%
            blue: 0%
    on_release:
      then:
        - light.addressable_set:
            id: led1
            range_from: 20
            range_to: 24
            red: 0%
            green: 100%
            blue: 100%   

# For Env-Unit Sensor
i2c:
  sda: 26
  scl: 32
  scan: True
  id: bus_a
  frequency: 100000

sensor:
  - <<: !include ../common/sensor/wifi_signal.yaml
  - <<: !include ../common/sensor/uptime.yaml
