substitutions:
  <<: !include ../secrets.yaml
  esphome_name: door_switch_lite_01

packages:
  device_base: !include ../common/m5lite_core.yaml

# For Door Sensor
binary_sensor:
  - platform: gpio
    pin:
      number: 22
      mode: INPUT_PULLUP
    name: "Living Door"
    device_class: door
    filters:
      - delayed_on: 100ms
    <<: !include ../common/sensor/m5lite_binsensor_effect.yaml

# For Env-Unit Sensor
i2c:
  sda: 26
  scl: 32
  scan: True
  id: bus_a
  frequency: 100000

sensor:
  - platform: dht12
    temperature:
      name: "Lite-01 DHT12-Temperature"
      unit_of_measurement: "°C"
    humidity:
      name: "Lite-01 DHT12-Humidity"
      unit_of_measurement: "%"
    update_interval: 60s
  - platform: bmp280
    temperature:
      name: "Lite-01 BMP280-Temperature"
      oversampling: 16x
    pressure:
      name: "Lite-01 BMP280-Pressure"
    address: 0x76
    update_interval: 60s
  - <<: !include ../common/sensor/wifi_signal.yaml
  - <<: !include ../common/sensor/uptime.yaml