substitutions:
  <<: !include ../secrets.yaml
  esphome_name: sonoff01

esphome:
  name: ${esphome_name}
  platform: ESP8266
  board: esp01_1m
  platformio_options:
    upload_speed: 115200

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}

api:
  password: ${api_password}

ota:
  password: ${ota_password}

logger:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff Basic Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Sonoff Basic Relay"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes