esphome:
  name: ${esphome_name}
  platform: ESP32
  board: pico32
  platformio_options:
    upload_speed: 115200
  on_boot:
    - light.turn_on:
        id: led1
        brightness: 30%
        red: 0%
        green: 0%
        blue: 100%
    - wait_until:
        wifi.connected:
    - light.turn_off: led1
    - light.turn_on:
        id: led1
        brightness: 30%
        red: 0%
        green: 100%
        blue: 0%
    - wait_until:
        api.connected:
    - light.turn_off: led1
    - light.turn_on:
        id: led1
        brightness: 30%
        red: 0%
        green: 50%
        blue: 50%

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${esphome_name}
    password: ${cap_passowrd}

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ${api_password}

ota:
  password: ${ota_password}

light:
  - platform: fastled_clockless
    chipset: SK6812
    pin: GPIO27
    num_leds: 1
    rgb_order: GRB
    name: ${esphome_name}_FastLED
    id: led1